### PR TITLE
chore(gradient-installer): optional ssh key path

### PR DESCRIPTION
**Pull request by marquiswashere**
- Making SSHKeyPath optional
- Adding paperspace api key override

### CODE REVIEW

**Review by sanfilip — APPROVED** [review]

**Comment by marquiswashere** [comment]
adding an extra commit, goofed with go pointers.

<img width="474" alt="Screen Shot 2022-01-25 at 12 24 41 AM" src="https://user-images.githubusercontent.com/95641952/150916401-7f8f011a-3f14-466c-bf67-50cecf932abe.png">

Terraform output:
```
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # module.gradient_metal.module.gradient_processing.data.kubernetes_service.traefik will be read during apply
  # (config refers to values not yet known)
 <= data "kubernetes_service" "traefik"  {
      + id     = (known after apply)
      + spec   = (known after apply)
      + status = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = (known after apply)
          + resource_version = (known after apply)
          + uid              = (known after apply)
        }
    }

  # module.gradient_metal.module.gradient_processing.helm_release.gradient_processing will be created
  + resource "helm_release" "gradient_processing" {
      + atomic                     = false
      + chart                      = "gradient-processing"
      + cleanup_on_fail            = false
      + create_namespace           = false
      + dependency_update          = false
      + disable_crd_hooks          = false
      + disable_openapi_validation = false
      + disable_webhooks           = false
      + force_update               = false
      + id                         = (known after apply)
      + lint                       = false
      + manifest                   = (known after apply)
      + max_history                = 0
      + metadata                   = (known after apply)
      + name                       = "gradient-processing"
      + namespace                  = "default"
      + recreate_pods              = false
      + render_subchart_notes      = true
      + replace                    = false
      + repository                 = "https://infrastructure-public-chart-museum-repository.storage.googleapis.com"
      + reset_values               = false
      + reuse_values               = false
      + skip_crds                  = false
      + status                     = "deployed"
      + timeout                    = 300
      + values                     = [
          + <<-EOT
                global:
                  amqpExchange: clm6exc77
                
                  artifactsPath: s3://marquis-test-bucket-1
                  cluster:
                    handle: clm6exc77
                    name: marquis-test-cluster-1
                  
                  elasticSearch:
                    host: b35b1cdf227c418b8353fd3b282527c5.us-east-1.aws.found.io
                    index: 
                    port: 9243
                    user: gradient
                  
                
                  logs:
                    host: logs.paperspace.io
                  ingressHost: domain1.io
                  clusterSecretChecksum: 29b2cbfe9c8079b4d17f423e07ba420c6f55c6b9bc38c53888aed7031b4e2863
                  serviceNodeSelector:
                    paperspace.com/pool-name: metal-gpu
                  serviceResources:
                    
                    requests:
                      cpu: 100m
                      memory: 128Mi
                    limits:
                      cpu: 100m
                      memory: 128Mi
                   
                
                  api: https://api.paperspace.io
                
                  defaultStorageName: gradient-processing-local
                  sharedStorageName: gradient-processing-shared
                  storage:
                    gradient-processing-local:
                      class: gradient-processing-local
                      path: /etc/nfs
                      server: 10.0.1.23
                      type: nfs
                
                      
                    gradient-processing-shared:
                      class: gradient-processing-shared
                      path: /etc/nfs
                      server: 10.0.1.23
                      type: nfs
                
                      
                
                ceph-csi-cephfs:
                  enabled: false
                  csiConfig:
                    
                    
                  provisioner:
                    nodeSelector:
                      paperspace.com/pool-name: metal-gpu
                
                # https://github.com/kubernetes-csi/external-provisioner/releases
                
                
                cluster-autoscaler:
                  enabled: false
                  
                  
                  resources:
                    limits:
                      cpu: 100m
                      memory: 512Mi
                    requests:
                      cpu: 100m
                      memory: 512Mi
                  
                
                  awsRegion: us-east-1
                  autoDiscovery:
                    clusterName: marquis-test-cluster-1
                  cloudProvider: 
                
                  nodeSelector:
                    paperspace.com/pool-name: metal-gpu
                
                dispatcher:
                  config:
                    apiAddress: dispatcher.paperspace.com
                
                
                efs-provisioner:
                  enabled: false
                  efsProvisioner:
                    awsRegion: us-east-1
                    efsFileSystemId: "10"
                    path: /etc/nfs
                  nodeSelector:
                    paperspace.com/pool-name: metal-gpu
                
                fluent-bit:
                  env:
                    - name: PS_LOGS_HOST
                      value: logs.paperspace.io
                    - name: PS_CLUSTER_HANDLE
                      value: clm6exc77
                    - name: PS_CLUSTER_AUTHORIZATION_TOKEN
                      valueFrom:
                        secretKeyRef:
                          name: gradient-processing
                          key: PS_CLUSTER_AUTHORIZATION_TOKEN
                
                gradient-operator:
                  config:
                    ingressHost: domain1.io
                    usePodAntiAffinity: false
                
                    
                
                    
                    
                    
                    
                
                    
                
                    abuseWatcher:
                      enabled: false
                      antiCryptoMinerRegex: 
                
                      
                
                    
                    modelDeploymentConfig:
                      labelName: paperspace.com/pool-name
                      cpu:
                        small:
                          label: metal-cpu
                        medium:
                          label: metal-cpu
                        large:
                          label: metal-cpu
                      gpu:
                        small:
                          label: metal-gpu
                          requests:
                            memory: 5Gi
                        medium:
                          label: metal-gpu
                          requests:
                            memory: 20Gi
                        large:
                          label: metal-gpu
                          requests:
                            memory: 58Gi
                
                    experimentConfig:
                      labelName: paperspace.com/pool-name
                      cpu:
                        small:
                          label: metal-cpu
                        medium:
                          label: metal-cpu
                        large:
                          label: metal-cpu
                      gpu:
                        small:
                          label: metal-gpu
                          requests:
                            memory: 5Gi
                        medium:
                          label: metal-gpu
                          requests:
                            memory: 20Gi
                        large:
                          label: metal-gpu
                          requests:
                            memory: 58Gi
                    notebookConfig:
                      labelName: paperspace.com/pool-name
                      cpu:
                        small:
                          label: metal-cpu
                        medium:
                          label: metal-cpu
                        large:
                          label: metal-cpu
                      gpu:
                        small:
                          label: metal-gpu
                          requests:
                            memory: 5Gi
                        medium:
                          label: metal-gpu
                          requests:
                            memory: 20Gi
                        large:
                          label: metal-gpu
                          requests:
                            memory: 58Gi
                    tensorboardConfig:
                      labelName: paperspace.com/pool-name
                      cpu:
                        small:
                          label: metal-cpu
                        medium:
                          label: metal-cpu
                        large:
                          label: metal-cpu
                      gpu:
                        small:
                          label: metal-gpu
                          requests:
                            memory: 5Gi
                        medium:
                          label: metal-gpu
                          requests:
                            memory: 20Gi
                        large:
                          label: metal-gpu
                          requests:
                            memory: 58Gi
                    
                
                gradient-metrics:
                  ingress:
                    hostPath:
                      domain1.io: /metrics
                  config:
                    newRelicEnabled: false
                    newRelicName: 
                
                gradient-operator-dispatcher:
                  config:
                    sentryEnvironment: marquis-test-cluster-1
                    sentryDSN: 
                
                nfs-subdir-external-provisioner:
                  enabled: true
                  nfs:
                    path: /etc/nfs
                    server: 10.0.1.23
                  nodeSelector:
                    paperspace.com/pool-name: metal-gpu
                
                victoria-metrics-k8s-stack:
                  vmsingle:
                    spec:
                      storage:
                        storageClassName: gradient-processing-local
                      
                      nodeSelector:
                        paperspace.com/pool-name: metal-gpu
                      
                    ingress:
                      hosts:
                        - domain1.io
                
                  kube-state-metrics:
                    
                    nodeSelector:
                      paperspace.com/pool-name: metal-gpu
                
                  victoria-metrics-operator:
                    
                    nodeSelector:
                      paperspace.com/pool-name: metal-gpu
                
                  vmagent:
                    spec:
                      externalLabels:
                        cluster: clm6exc77
                      nodeSelector:
                        paperspace.com/pool-name: metal-gpu
                      
                
                traefik:
                  replicas: 1
                  nodeSelector:
                    paperspace.com/pool-name: metal-gpu
                
                  affinity:
                    podAntiAffinity:
                      preferredDuringSchedulingIgnoredDuringExecution:
                      - weight: 100
                        podAffinityTerm:
                          topologyKey: "kubernetes.io/hostname"
                
                  
                  serviceType: NodePort
                  deploymentStrategy:
                    type: Recreate
                  deployment:
                    hostNetwork: true
                    hostPort:
                      httpEnabled: true
                      httpPort: 80
                      httpsEnabled: true
                      httpsPort: 443
                  
                
                  
                
                  
                
                argo:
                  controller:
                    nodeSelector:
                      paperspace.com/pool-name: metal-gpu
                
                argo-rollouts:
                  controller:
                    nodeSelector:
                      paperspace.com/pool-name: metal-gpu
                
                    requests:
                      cpu: 100m
                      memory: 128Mi
                    limits:
                      cpu: 100m
                      memory: 128Mi
                
                
                
                
                
                volumeController:
                  enabled: true
                  
                
                recycleBin:
                  enabled: true
                  
                
                
                
            EOT,
        ]
      + verify                     = false
      + version                    = "v0.46.7"
      + wait                       = true
      + wait_for_jobs              = false

      + set_sensitive {
          + name  = "global.artifactsAccessKeyId"
          + value = (sensitive value)
        }
      + set_sensitive {
          + name  = "global.artifactsSecretAccessKey"
          + value = (sensitive value)
        }
      + set_sensitive {
          + name  = "global.elasticSearch.password"
          + value = (sensitive value)
        }
      + set_sensitive {
          + name = "gradient-metrics.config.newRelicKey"
        }
      + set_sensitive {
          + name  = "secrets.amqpUri"
          + value = (sensitive value)
        }
      + set_sensitive {
          + name  = "secrets.clusterApikey"
          + value = (sensitive value)
        }
      + set_sensitive {
          + name  = "secrets.clusterAuthorizationToken"
          + value = (sensitive value)
        }
      + set_sensitive {
          + name  = "secrets.tlsCert"
          + value = (sensitive value)
        }
      + set_sensitive {
          + name  = "secrets.tlsKey"
          + value = (sensitive value)
        }
      + set_sensitive {
          + name  = "traefik.acme.dnsProvider.name"
          + value = (sensitive value)
        }
      + set_sensitive {
          + name  = "traefik.ssl.defaultCert"
          + value = (sensitive value)
        }
      + set_sensitive {
          + name  = "traefik.ssl.defaultKey"
          + value = (sensitive value)
        }
    }

  # module.gradient_metal.module.kubernetes.local_file.kubeconfig[0] will be created
  + resource "local_file" "kubeconfig" {
      + content              = (sensitive)
      + directory_permission = "0777"
      + file_permission      = "0777"
      + filename             = "./gradient-kubeconfig"
      + id                   = (known after apply)
    }

  # module.gradient_metal.module.kubernetes.null_resource.rke_nodes_wait[0] will be created
  + resource "null_resource" "rke_nodes_wait" {
      + id = (known after apply)
    }

  # module.gradient_metal.module.kubernetes.rke_cluster.main will be created
  + resource "rke_cluster" "main" {
      + api_server_url            = (known after apply)
      + ca_crt                    = (sensitive value)
      + certificates              = (sensitive value)
      + client_cert               = (sensitive value)
      + client_key                = (sensitive value)
      + cluster_cidr              = (known after apply)
      + cluster_dns_server        = (known after apply)
      + cluster_domain            = (known after apply)
      + cluster_name              = "marquis-test-cluster-1"
      + control_plane_hosts       = (known after apply)
      + custom_certs              = false
      + dind                      = false
      + disable_port_check        = false
      + etcd_hosts                = (known after apply)
      + id                        = (known after apply)
      + inactive_hosts            = (known after apply)
      + internal_kube_config_yaml = (sensitive value)
      + kube_admin_user           = (known after apply)
      + kube_config_yaml          = (sensitive value)
      + kubernetes_version        = "v1.20.8-rancher1-1"
      + rke_cluster_yaml          = (sensitive value)
      + rke_state                 = (sensitive value)
      + running_system_images     = (known after apply)
      + ssh_agent_auth            = true
      + update_only               = false
      + worker_hosts              = (known after apply)

      + authentication {
          + sans     = []
          + strategy = "x509"

          + webhook {
              + cache_timeout = (known after apply)
              + config_file   = (known after apply)
            }
        }

      + ingress {
          + default_backend = true
          + provider        = "none"
        }

      + nodes {
          + address        = "192.168.10.1"
          + docker_socket  = "/var/run/docker.sock"
          + labels         = {
              + "node-role.kubernetes.io/controller" = "true"
              + "node-role.kubernetes.io/master"     = ""
              + "paperspace.com/pool-name"           = "metal-gpu"
              + "paperspace.com/pool-type"           = "gpu"
            }
          + role           = [
              + "controlplane",
              + "etcd",
              + "worker",
            ]
          + ssh_agent_auth = (known after apply)
          + user           = (sensitive value)
        }

      + services {
          + etcd {
              + ca_cert       = (sensitive value)
              + cert          = (sensitive value)
              + creation      = (known after apply)
              + external_urls = (known after apply)
              + extra_args    = (known after apply)
              + extra_binds   = (known after apply)
              + extra_env     = (known after apply)
              + gid           = (known after apply)
              + image         = (known after apply)
              + key           = (sensitive value)
              + path          = (known after apply)
              + retention     = (known after apply)
              + snapshot      = (known after apply)
              + uid           = (known after apply)

              + backup_config {
                  + enabled        = (known after apply)
                  + interval_hours = (known after apply)
                  + retention      = (known after apply)
                  + safe_timestamp = (known after apply)
                  + timeout        = (known after apply)

                  + s3_backup_config {
                      + access_key  = (sensitive value)
                      + bucket_name = (known after apply)
                      + custom_ca   = (known after apply)
                      + endpoint    = (known after apply)
                      + folder      = (known after apply)
                      + region      = (known after apply)
                      + secret_key  = (sensitive value)
                    }
                }
            }

          + kube_api {
              + always_pull_images       = (known after apply)
              + extra_args               = (known after apply)
              + extra_binds              = (known after apply)
              + extra_env                = (known after apply)
              + image                    = (known after apply)
              + pod_security_policy      = (known after apply)
              + service_cluster_ip_range = (known after apply)
              + service_node_port_range  = (known after apply)

              + audit_log {
                  + enabled = (known after apply)

                  + configuration {
                      + format     = (known after apply)
                      + max_age    = (known after apply)
                      + max_backup = (known after apply)
                      + max_size   = (known after apply)
                      + path       = (known after apply)
                      + policy     = (known after apply)
                    }
                }

              + event_rate_limit {
                  + configuration = (known after apply)
                  + enabled       = (known after apply)
                }

              + secrets_encryption_config {
                  + custom_config = (known after apply)
                  + enabled       = (known after apply)
                }
            }

          + kube_controller {
              + cluster_cidr             = (known after apply)
              + extra_args               = (known after apply)
              + extra_binds              = (known after apply)
              + extra_env                = (known after apply)
              + image                    = (known after apply)
              + service_cluster_ip_range = (known after apply)
            }

          + kubelet {
              + cluster_dns_server           = (known after apply)
              + cluster_domain               = "cluster.local"
              + extra_args                   = (known after apply)
              + extra_binds                  = []
              + extra_env                    = (known after apply)
              + fail_swap_on                 = (known after apply)
              + generate_serving_certificate = false
              + image                        = (known after apply)
              + infra_container_image        = (known after apply)
            }

          + kubeproxy {
              + extra_args  = (known after apply)
              + extra_binds = (known after apply)
              + extra_env   = (known after apply)
              + image       = (known after apply)
            }

          + scheduler {
              + extra_args  = (known after apply)
              + extra_binds = (known after apply)
              + extra_env   = (known after apply)
              + image       = (known after apply)
            }
        }

      + system_images {
          + kubernetes = "rancher/hyperkube:v1.20.8-rancher1"
        }

      + upgrade_strategy {
          + drain                        = false
          + max_unavailable_controlplane = "1"
          + max_unavailable_worker       = "10%"

          + drain_input {
              + delete_local_data  = (known after apply)
              + force              = (known after apply)
              + grace_period       = (known after apply)
              + ignore_daemon_sets = (known after apply)
              + timeout            = (known after apply)
            }
        }
    }

Plan: 4 to add, 0 to change, 0 to destroy.
```

**Comment by marquiswashere** [comment]
Previously we saw what happens if we swap the prompt for required and have an intermediate variable so that the ssh key path is "optionally" passed to terraform or not (the plan succeeds). 

Here's some unhappy paths:

Using `""` 

Screen Shot 2022-01-25 at 12 30 49 AM
 
 Using a `[space]` character
Screen Shot 2022-01-25 at 12 35 27 AM

I think we're pretty aligned on, we can skip the ssh key prompt by having the user simply press enter. All other user input validation we can tackle in another PR.

@sanfilip can you give this another once over when you get a chance?

**Review by sanfilip — APPROVED** [review]
Approving assuming you tested this.

**Comment by marquiswashere** [comment]
@sanfilip yeah that's the screenshots, can put this on hold if you want to test as well in this branch.

**Comment by marquiswashere** [comment]
Closing PR.

**Pull request merged**
